### PR TITLE
Added union and intersection of 2 arrays

### PR DESCRIPTION
**Pull request by DeveshBaranwal**
Please label it as hacktoberfest

### CODE REVIEW

**Review by DeveshBaranwal — COMMENTED** [review]
Added max min array file

**Comment by DeveshBaranwal** [comment]
Added sorting of  0s 1s and 2s without using sorting algorithm
Please mark it as hacktoberfest accepted

**Comment by shuchitpant** [comment]
Bernie bwoi!!

**Comment by DeveshBaranwal** [comment]
Bhai

Ek aur bheja hai
Code to reverse last 5 nodes of linked list
Please label it as hacktoberfest accepted.

**Pull request merged**
